// Seed content for Reely — creators, viewers, mini-series, videos, and the
// prebuilt channel lineup. Video files are generated by generate-videos.mjs
// from these same specs.

export const DEMO_PASSWORD = "reely123";

export const CREATORS = [
  {
    username: "maya_makes",
    displayName: "Maya Makes",
    avatarEmoji: "🍳",
    avatarColor: "#F4A26B",
    bio: "Tiny kitchen, big flavors.",
    creatorAbout:
      "I started filming one-minute recipes on my lunch break, and it turned into a whole show. Everything is cooked in my real (tiny!) kitchen — no food styling tricks, just honest cooking sped up to sixty seconds.",
    creatorTools: ["iPhone 15", "tripod clamp", "CapCut", "clip-on macro lens"],
    creatorProcess:
      "I write a 6-shot storyboard on a sticky note, cook the dish twice (once to test, once to film), then edit the same evening. One minute of video is about two hours of work.",
  },
  {
    username: "the_dramatist",
    displayName: "The Dramatist",
    avatarEmoji: "🎭",
    avatarColor: "#CDB4DB",
    bio: "Cliffhangers in sixty seconds.",
    creatorAbout:
      "Former theater kid, current microdrama addict. I write, direct, and act in tiny episodes with two friends and one very patient camera operator. If you gasp on the bus, my job is done.",
    creatorTools: ["Sony ZV-E10", "DaVinci Resolve", "two clip lights", "lapel mics"],
    creatorProcess:
      "Every series is written as six one-minute beats, each ending on a question. We shoot a whole series in one Saturday.",
  },
  {
    username: "daily_spark",
    displayName: "Daily Spark",
    avatarEmoji: "⚡",
    avatarColor: "#F2B01E",
    bio: "One spark a day keeps the couch away.",
    creatorAbout:
      "Retired PE teacher. I make one minute of honest encouragement every morning — no yelling, no hustle-culture, just a warm nudge to keep going.",
    creatorTools: ["Pixel 9", "coffee", "sunrise"],
    creatorProcess: "Filmed in one take on my morning walk. If I stumble on a word, that stays in — real beats perfect.",
  },
  {
    username: "whodunit_wanda",
    displayName: "Whodunit Wanda",
    avatarEmoji: "🕵️",
    avatarColor: "#8ECAE6",
    bio: "Every minute hides a clue.",
    creatorAbout:
      "Mystery writer who got tired of novels taking two years. Now I hide a solvable mystery in every sixty-second episode. Pause, rewind, comment your theory at the exact second you spotted the clue.",
    creatorTools: ["Canon M50", "string board", "red yarn", "Premiere Pro"],
    creatorProcess:
      "I design the clue first, then build the scene around it. The answer is always on screen for at least two seconds. Play fair, solve fast.",
  },
  {
    username: "pet_theater",
    displayName: "Pet Theater",
    avatarEmoji: "🐾",
    avatarColor: "#B7E4C7",
    bio: "My pets have an agent now.",
    creatorAbout:
      "It started when my cat walked through my home office on a video call and stole the meeting. Now Biscuit the cat and Waffle the corgi star in their own tiny shows.",
    creatorTools: ["GoPro", "treat pouch", "infinite patience"],
    creatorProcess:
      "You cannot direct a cat. You can only film for an hour and keep the eight seconds where she does something incredible.",
  },
  {
    username: "lens_and_light",
    displayName: "Lens & Light",
    avatarEmoji: "🎬",
    avatarColor: "#94D2BD",
    bio: "How the tiny shows get made.",
    creatorAbout:
      "Cinematographer by day. I break down how creators shoot their minis — lighting on a budget, sound in a closet, edits that make one phone look like a film crew.",
    creatorTools: ["whiteboard", "LumaFusion", "every camera I can borrow"],
    creatorProcess: "One technique per episode, shown twice: once badly, once well. The difference teaches itself.",
  },
];

export const VIEWERS = [
  { username: "demo", displayName: "Demo Watcher", avatarEmoji: "🙂", avatarColor: "#FFD166" },
  { username: "grandma_rose", displayName: "Grandma Rose", avatarEmoji: "🌹", avatarColor: "#FFC8DD" },
  { username: "kiddo_max", displayName: "Max", avatarEmoji: "🦖", avatarColor: "#BDE0FE" },
  { username: "movie_mike", displayName: "Movie Mike", avatarEmoji: "🎥", avatarColor: "#A8DADC" },
  { username: "sunny_sam", displayName: "Sunny Sam", avatarEmoji: "🌞", avatarColor: "#E9C46A" },
  { username: "night_owl", displayName: "Night Owl", avatarEmoji: "🦉", avatarColor: "#CDB4DB" },
  { username: "binge_bee", displayName: "Binge Bee", avatarEmoji: "🐝", avatarColor: "#F2B01E" },
  { username: "quiet_quinn", displayName: "Quiet Quinn", avatarEmoji: "🐢", avatarColor: "#94D2BD" },
];

// Gradient palettes per category (hex without #, ffmpeg 0xRRGGBB).
export const CATEGORY_STYLE = {
  comedy: ["FF8FA3", "FFD166"],
  drama: ["6D597A", "B56576"],
  motivation: ["F2B01E", "E8503A"],
  mystery: ["22223B", "4A4E69"],
  romance: ["FFAFCC", "CDB4DB"],
  thriller: ["1B263B", "415A77"],
  food: ["F4A26B", "E76F51"],
  animals: ["80B918", "55A630"],
  learning: ["4EA8DE", "5E60CE"],
  travel: ["48CAE4", "023E8A"],
  music: ["9D4EDD", "5A189A"],
  kids: ["FFD166", "06D6A0"],
};

export const SERIES = [
  {
    key: "breakroom",
    title: "The Break Room",
    creator: "the_dramatist",
    description: "Three coworkers. One microwave. Endless drama.",
  },
  {
    key: "locket",
    title: "The Lost Locket",
    creator: "whodunit_wanda",
    description: "A locket goes missing at the family reunion. Everyone is a suspect.",
  },
  {
    key: "coffee",
    title: "Coffee & Courage",
    creator: "the_dramatist",
    description: "Two strangers, one café, six tiny episodes to say hello.",
  },
];

// slug, title, creator, category, tags, dur (sec), series/ep, backstory,
// description, quality: 'great' | 'good' | 'mixed' | 'poor' (drives ratings).
export const VIDEOS = [
  // — The Break Room (comedy microdrama series)
  { slug: "breakroom-ep1", title: "The Last Yogurt", creator: "the_dramatist", category: "comedy", tags: ["sitcom", "office", "series"], dur: 12, series: "breakroom", ep: 1, quality: "great",
    description: "Someone ate Deb's yogurt. Deb knows.",
    backstory: "We shot this in our real office after hours. The fridge hum you hear is genuine — we decided it was basically a character." },
  { slug: "breakroom-ep2", title: "Reply All", creator: "the_dramatist", category: "comedy", tags: ["sitcom", "office", "series"], dur: 11, series: "breakroom", ep: 2, quality: "great",
    description: "Gary hit reply all. To everyone. Including the CEO.",
    backstory: "Based on a true story that happened to me. The panic is method acting." },
  { slug: "breakroom-ep3", title: "The Microwave Truce", creator: "the_dramatist", category: "comedy", tags: ["sitcom", "office", "series"], dur: 13, series: "breakroom", ep: 3, quality: "good",
    description: "Fish in the microwave. The building votes.",
    backstory: "Episode three took nine takes because we kept laughing. Kept take nine anyway — you can see the smile break at the end." },
  // — The Lost Locket (mystery series)
  { slug: "locket-ep1", title: "Gone Before Dessert", creator: "whodunit_wanda", category: "mystery", tags: ["whodunit", "family", "series"], dur: 14, series: "locket", ep: 1, quality: "great",
    description: "Grandma's locket vanishes between the salad and the pie.",
    backstory: "The clue is visible at exactly 0:06. Nobody has found it on first watch yet. Comment the timecode if you do." },
  { slug: "locket-ep2", title: "Three Alibis", creator: "whodunit_wanda", category: "mystery", tags: ["whodunit", "family", "series"], dur: 12, series: "locket", ep: 2, quality: "good",
    description: "Everyone has an alibi. One of them is lying.",
    backstory: "I wrote the alibis so all three are technically true. Listen to WHAT they deny — not how." },
  { slug: "locket-ep3", title: "The Pocket Reveal", creator: "whodunit_wanda", category: "mystery", tags: ["whodunit", "family", "series"], dur: 13, series: "locket", ep: 3, quality: "great",
    description: "The locket was never lost. It was hidden. Here is why.",
    backstory: "The reveal shot took a whole afternoon — we needed the locket to catch the light at the exact moment." },
  // — Coffee & Courage (romance series)
  { slug: "coffee-ep1", title: "Same Order Again", creator: "the_dramatist", category: "romance", tags: ["meetcute", "cafe", "series"], dur: 11, series: "coffee", ep: 1, quality: "good",
    description: "He orders the same thing every day. Today she noticed.",
    backstory: "Filmed in a real café before opening. The barista is the owner — she demanded a cameo as payment." },
  { slug: "coffee-ep2", title: "The Wrong Cup", creator: "the_dramatist", category: "romance", tags: ["meetcute", "cafe", "series"], dur: 12, series: "coffee", ep: 2, quality: "good",
    description: "Two cups, two names, one very lucky mix-up.",
    backstory: "The cup swap is one unbroken shot. We practiced the hand-off eleven times." },
  { slug: "coffee-ep3", title: "Say It Before Monday", creator: "the_dramatist", category: "romance", tags: ["meetcute", "cafe", "series"], dur: 13, series: "coffee", ep: 3, quality: "mixed",
    description: "The café closes for renovations. It is now or never.",
    backstory: "We argued about the ending for a week. The version you see won by one vote — mine." },
  // — Standalone comedy
  { slug: "wifi-down", title: "The Day The WiFi Died", creator: "the_dramatist", category: "comedy", tags: ["family", "chaos"], dur: 10, quality: "good",
    description: "A family rediscovers board games. Badly.",
    backstory: "My actual family. Nobody was acting." },
  { slug: "gps-argument", title: "Recalculating", creator: "the_dramatist", category: "comedy", tags: ["roadtrip", "couple"], dur: 9, quality: "mixed",
    description: "The GPS says left. Dad says right. The GPS is crying.",
    backstory: "Recorded the GPS voice myself with a towel over my head for that muffled speaker sound." },
  // — Motivation
  { slug: "spark-monday", title: "Monday Is Not The Enemy", creator: "daily_spark", category: "motivation", tags: ["morning", "peptalk"], dur: 10, quality: "great",
    description: "Sixty seconds to reset how you see the week.",
    backstory: "Filmed the morning after I really did not want to get up. That is why it works." },
  { slug: "spark-smallwins", title: "Count The Small Wins", creator: "daily_spark", category: "motivation", tags: ["habits", "peptalk"], dur: 11, quality: "good",
    description: "Made your bed? That counts. It all counts.",
    backstory: "My granddaughter told me making her bed felt pointless. This one is for her." },
  { slug: "spark-restday", title: "Rest Is Training Too", creator: "daily_spark", category: "motivation", tags: ["rest", "peptalk"], dur: 9, quality: "good",
    description: "The most productive thing you can do today might be nothing.",
    backstory: "A PE teacher telling you to rest — I know. Thirty years taught me this one the hard way." },
  // — Food
  { slug: "onepan-pasta", title: "One Pan Pasta Magic", creator: "maya_makes", category: "food", tags: ["recipe", "pasta", "easy"], dur: 12, quality: "great",
    description: "Dinner in one pan, one minute, zero stress.",
    backstory: "Tested this seven times to get the timing honest. Yes, the pasta really cooks in the sauce." },
  { slug: "threeegg-omelette", title: "The Three Egg Rule", creator: "maya_makes", category: "food", tags: ["recipe", "breakfast", "easy"], dur: 10, quality: "good",
    description: "Why three eggs make a better omelette than two or four.",
    backstory: "My grandmother's rule. I doubted it on camera and was proven wrong in real time." },
  { slug: "midnight-toastie", title: "Midnight Toastie", creator: "maya_makes", category: "food", tags: ["recipe", "snack"], dur: 9, quality: "mixed",
    description: "The 11pm sandwich that fixes everything.",
    backstory: "Filmed at actual midnight in pajamas. The crunch at 0:07 is real and I think about it weekly." },
  // — Animals
  { slug: "biscuit-heist", title: "The Great Biscuit Heist", creator: "pet_theater", category: "animals", tags: ["cat", "funny"], dur: 8, quality: "great",
    description: "Biscuit the cat plans the perfect crime.",
    backstory: "One hour of filming for eight perfect seconds. Worth it." },
  { slug: "waffle-doorbell", title: "Waffle vs The Doorbell", creator: "pet_theater", category: "animals", tags: ["dog", "funny"], dur: 10, quality: "good",
    description: "The corgi has opinions about visitors.",
    backstory: "We rang our own doorbell forty times for this. Our neighbors have questions." },
  { slug: "biscuit-boxfort", title: "Box Fort Kingdom", creator: "pet_theater", category: "animals", tags: ["cat", "cozy"], dur: 11, quality: "good",
    description: "We built Biscuit a castle. She chose the tiny box it came in.",
    backstory: "The castle took three hours to build. She sat in it once, out of pity." },
  // — Thriller
  { slug: "knock-at-nine", title: "The Knock At Nine", creator: "whodunit_wanda", category: "thriller", tags: ["spooky", "kidsafe"], dur: 13, quality: "good",
    description: "Every night at nine, three knocks. Tonight she answers.",
    backstory: "Kid-safe scary is the hardest genre — the reveal has to make you laugh with relief." },
  { slug: "wrong-reflection", title: "The Wrong Reflection", creator: "whodunit_wanda", category: "thriller", tags: ["spooky", "twist"], dur: 12, quality: "mixed",
    description: "The mirror is a second behind. Watch closely.",
    backstory: "The delay effect is done with two identical shirts and my very patient twin sister." },
  // — Learning / behind the scenes
  { slug: "light-lamp", title: "Film Like A Pro With One Lamp", creator: "lens_and_light", category: "learning", tags: ["howto", "filmmaking", "budget"], dur: 14, quality: "great",
    description: "Your desk lamp is a film light. Here is the angle.",
    backstory: "The before and after in this one convinced three friends to start making videos. That is the whole point." },
  { slug: "closet-sound", title: "Why Closets Sound Amazing", creator: "lens_and_light", category: "learning", tags: ["howto", "audio", "budget"], dur: 12, quality: "good",
    description: "Record your voiceover in the closet. Seriously.",
    backstory: "Recorded half this episode in the closet and half outside it, so you can hear exactly what the clothes do." },
  { slug: "phone-dolly", title: "The Skateboard Dolly Shot", creator: "lens_and_light", category: "learning", tags: ["howto", "filmmaking", "budget"], dur: 11, quality: "good",
    description: "Cinematic camera moves with a skateboard and tape.",
    backstory: "Yes, I fell off. No, that take is not in the episode. Yes, my sister has it saved." },
  // — Travel
  { slug: "alley-noodles", title: "The Alley Noodle Stand", creator: "maya_makes", category: "travel", tags: ["streetfood", "hiddengem"], dur: 13, quality: "good",
    description: "The best noodles in the city have no sign and six stools.",
    backstory: "The owner let me film only after I finished two bowls. Fair terms." },
  { slug: "sunrise-ferry", title: "The 6am Ferry", creator: "daily_spark", category: "travel", tags: ["morning", "calm"], dur: 10, quality: "mixed",
    description: "Sixty seconds of the quietest commute on earth.",
    backstory: "No talking in this one. Some minutes speak for themselves." },
  // — Drama
  { slug: "voicemail", title: "The Saved Voicemail", creator: "the_dramatist", category: "drama", tags: ["family", "tearjerker"], dur: 14, quality: "great",
    description: "She saves one voicemail. Today she plays it.",
    backstory: "We wrote this after my co-writer found a voicemail from her grandfather. She approved every frame." },
  { slug: "last-lightson", title: "Lights On For Nobody", creator: "the_dramatist", category: "drama", tags: ["neighbors", "quiet"], dur: 12, quality: "mixed",
    description: "The corner shop keeps its lights on for one customer who moved away.",
    backstory: "Shot through a real shop window at closing time. The owner watched the final cut and just nodded." },
  // — Music
  { slug: "bus-stop-band", title: "The Bus Stop Band", creator: "lens_and_light", category: "music", tags: ["street", "acoustic"], dur: 11, quality: "good",
    description: "Three strangers, one bus delay, an accidental band.",
    backstory: "I filmed this on my commute. The bus came too soon. Nobody wanted it to." },
  { slug: "kitchen-drums", title: "Kitchen Drum Solo", creator: "pet_theater", category: "music", tags: ["funny", "diy"], dur: 8, quality: "mixed",
    description: "Pots. Pans. One wooden spoon. Zero regrets.",
    backstory: "Biscuit the cat left the room in protest at 0:04. Watch for the tail." },
  // — Kids
  { slug: "sock-puppet-news", title: "Sock Puppet Evening News", creator: "pet_theater", category: "kids", tags: ["silly", "puppets"], dur: 10, quality: "good",
    description: "Tonight's top story: bedtime remains unfair.",
    backstory: "My kid wrote the headlines. I just held the socks." },
  { slug: "floor-is-lava", title: "The Floor Is Lava Olympics", creator: "daily_spark", category: "kids", tags: ["games", "family"], dur: 9, quality: "good",
    description: "Official rules, medal ceremony, one very dramatic fall.",
    backstory: "The judges (grandkids) were harsh but fair. I got silver." },
];

export const PREBUILT_CHANNELS = [
  { slug: "surprise-me", name: "Surprise Me", emoji: "🎲", kind: "surprise", category: "mixed",
    description: "Spin the dial. Something great, every time." },
  { slug: "weekly-best", name: "This Week's Best", emoji: "🏆", kind: "weekly", category: "mixed",
    description: "The top-rated videos of the week, updated automatically." },
  { slug: "laugh-track", name: "The Laugh Track", emoji: "😂", kind: "normal", category: "comedy",
    description: "One-minute comedies and running gags." },
  { slug: "mini-dramas", name: "Mini Dramas", emoji: "🎭", kind: "normal", category: "drama",
    description: "Cliffhangers in sixty seconds." },
  { slug: "get-up-and-go", name: "Get Up & Go", emoji: "💪", kind: "normal", category: "motivation",
    description: "Pep talks and comeback stories." },
  { slug: "whodunit-lane", name: "Whodunit Lane", emoji: "🕵️", kind: "normal", category: "mystery",
    description: "Bite-size mysteries and plot twists." },
  { slug: "meet-cute", name: "Meet Cute", emoji: "❤️", kind: "normal", category: "romance",
    description: "Tiny love stories, episode by episode." },
  { slug: "goosebump-alley", name: "Goosebump Alley", emoji: "😱", kind: "normal", category: "thriller",
    description: "Mildly spooky mini-thrillers. Kid-safe scary." },
  { slug: "made-from-scratch", name: "Made From Scratch", emoji: "🍳", kind: "normal", category: "food",
    description: "Cooking, crafts, and how-it's-made minis." },
  { slug: "critter-corner", name: "Critter Corner", emoji: "🐾", kind: "normal", category: "animals",
    description: "Animal stars in their own tiny shows." },
  { slug: "behind-the-curtain", name: "Behind the Curtain", emoji: "🎬", kind: "normal", category: "learning",
    description: "Creators show how they made it — gear, tricks, bloopers." },
  { slug: "small-world", name: "Small World", emoji: "🌍", kind: "normal", category: "travel",
    description: "Tiny trips and hidden gems." },
  { slug: "jukebox", name: "The Jukebox", emoji: "🎵", kind: "normal", category: "music",
    description: "Street sounds and tiny concerts." },
  { slug: "kids-corner", name: "Kids Corner", emoji: "🧸", kind: "normal", category: "kids",
    description: "Silly little shows for little people." },
];

export const SEED_COMMENTS = [
  { text: "I gasped out loud on the bus. Ten out of ten.", tc: true },
  { text: "Watched this three times and it gets better every time.", tc: false },
  { text: "THE CLUE IS RIGHT THERE. I finally saw it!", tc: true },
  { text: "My grandma and I both loved this one.", tc: false },
  { text: "This exact moment is perfect.", tc: true },
  { text: "How is this only a minute long, it feels like a whole movie.", tc: false },
  { text: "The timing here is incredible.", tc: true },
  { text: "Okay this deserves extra butter.", tc: false },
  { text: "I showed this to everyone at dinner.", tc: false },
  { text: "Please make a season two!", tc: false },
  { text: "This part made me laugh so hard.", tc: true },
  { text: "Tried this myself and it actually works!", tc: false },
];
